application/analytics_project/settings.py, application/workprogramsapp/serializers.py, application/workprogramsapp/urls.py, application/workprogramsapp/views.py
Добавлено:
GET/PUT для компетенции, 
POST для удаления индикатора из компетенции, 
POST для добавления индикатора в компетенцию,
GET/PUT для индикатора
Также изменены настройки rest_framework
=> Редактор компетенции, Редактор индикатора, Редактор индикатора в компетенции

application/workprogramsapp/views.py
Добавила обработку выборности, попробуйте, пожалуйста, с фронтом посмотреть. По записям дублей не должно быть в модулях блоков, как в прошлый раз
=> Обновление парсера

application/workprogramsapp/models.py, application/workprogramsapp/serializers.py, application/workprogramsapp/views.py, docker-compose.yml
Fixed bugs on deleting topics and disciplines, adding semesters began to work correctly
=> Fixed bugs

application/workprogramsapp/__init__.py, application/workprogramsapp/admin.py, application/workprogramsapp/apps.py, application/workprogramsapp/expertise/views.py, application/workprogramsapp/folders_ans_statistic/models.py, application/workprogramsapp/folders_ans_statistic/serializers.py, application/workprogramsapp/folders_ans_statistic/views.py, application/workprogramsapp/permissions.py, application/workprogramsapp/signals.py, application/workprogramsapp/urls.py, application/workprogramsapp/views.py
Created permissions to different groups of users, all groups are automaticly creating after first migrations. Also added api, that shows all groups which realted with request user
=> Users groups api and permissions

application/analytics_project/settings.py, application/dataprocessing/itmo_backends.py, application/dataprocessing/urls.py
Добавлен /api/cas-redirect/ для редиректа на CAS авторизацию и /login для обработки ответа
В env файле необходимо задать:
ISU_CLIENT_ID=""
ISU_CLIENT_SECRET=""
ISU_REDIRECT_URI=""
В dataprocessing/itmo_backends.py у AuthenticateByCodeISU в ответе можно поменять путь до фронта, где будет проходить авторизация
=> ISU CAS Auth

frontend/src/components/Menu/MenuList.tsx, frontend/src/containers/EducationalProgram/Characteristic/Characteristic.styles.ts, frontend/src/containers/Profile/Folders/Folders.styles.ts, frontend/src/containers/SelectEducationalProgram/EducationalProgramsTable/EducationalProgramsTable.style.ts, frontend/src/containers/SelectEducationalProgram/EducationalProgramsTable/EducationalProgramsTable.tsx, frontend/src/containers/SelectEducationalProgram/SelectEducationalProgram.styles.ts, frontend/src/containers/SelectEducationalProgram/SelectEducationalProgram.tsx, frontend/src/layout/Layout.js, frontend/src/layout/Layout.styles.js
Возможно проблемы небольшие проблемы с версткой на разных компонентах. Постарался пробежаться, вроде где увидел подправил. В случае проблем с версткой первым делом необходимо обратить внимание на высоту в стилях
=> Change title (Select Edu Program by professions), add custom scroll in Layout

frontend/src/containers/EducationalPlan/TrainingModules/DetailTrainingModule/DetailTrainingModule.styles.ts, frontend/src/containers/EducationalPlan/TrainingModules/DetailTrainingModule/DetailTrainingModule.tsx, frontend/src/containers/EducationalPlan/TrainingModules/TrainingModules.tsx, frontend/src/containers/WorkProgram/EvaluationTools/EvaluationTools.styles.ts, frontend/src/containers/WorkProgram/EvaluationTools/EvaluationTools.tsx, frontend/src/containers/WorkProgram/IntermediateCertification/IntermediateCertification.styles.ts, frontend/src/containers/WorkProgram/IntermediateCertification/IntermediateCertification.tsx, frontend/src/containers/WorkProgram/Literature/Literature.styles.ts, frontend/src/containers/WorkProgram/Literature/Literature.tsx, frontend/src/containers/WorkProgram/PlansAndDirections/PlansAndDirections.tsx, frontend/src/containers/WorkProgram/Prerequisites/Prerequisites.styles.ts, frontend/src/containers/WorkProgram/Prerequisites/Prerequisites.tsx, frontend/src/containers/WorkProgram/Results/Results.styles.ts, frontend/src/containers/WorkProgram/Results/Results.tsx, frontend/src/containers/WorkProgram/Sections/Sections.styles.ts, frontend/src/containers/WorkProgram/Sections/Sections.tsx, frontend/src/containers/WorkProgram/Topics/ThemeCreateModal/ThemeCreateModal.tsx, frontend/src/containers/WorkProgram/Topics/Topics.styles.ts, frontend/src/containers/WorkProgram/Topics/Topics.tsx, frontend/src/containers/WorkProgram/WorkProgram.styles.ts, frontend/src/containers/WorkProgram/WorkProgram.tsx, frontend/src/layout/Layout.js
Исправленные баги:
В разделе "Учебные модули" при открытии модалки не исчезают опции
В подробностях учебного модуля при открытом меню на низком разрешении баг и с иконками
Улучшена адаптивность в редакторе РПД
=> fixd bugs, improve adapatbility

application/analytics_project/settings.py, application/workprogramsapp/individualization/urls.py, application/workprogramsapp/individualization/views.py, application/workprogramsapp/op_slection/views.py
url: api/individualization/save_for_user
sample: {"implementation_set":[]} -  в список передаются id для IndividualImplementationAcademicPlan
=> save individual routes after selection

frontend/src/containers/EducationalPlan/EducationalPlan.tsx, frontend/src/containers/Expertises/Expertise/Expertise.connect.ts, frontend/src/containers/Expertises/Expertise/Expertise.tsx, frontend/src/containers/Expertises/Expertises.tsx, frontend/src/containers/Expertises/enum.ts, frontend/src/containers/Expertises/getters.ts
EX, SE, AU in experts in Expertises list. AU, EX in expertise detail
fix user rules in expertise detail
=> show experts (EX, SE, AU) in Expertises list, fix user rules in expertise detail

frontend/src/components/Header/Header.tsx, frontend/src/containers/DodProfile/DodProfile.tsx, frontend/src/containers/MergeWorkPrograms/index.tsx
=> Фиксы личного кабинета редактора

frontend/src/containers/WorkProgram/validation.ts
=> fix checks texts

frontend/src/containers/MergeWorkPrograms/actions.ts, frontend/src/containers/MergeWorkPrograms/enum.ts, frontend/src/containers/MergeWorkPrograms/getters.ts, frontend/src/containers/MergeWorkPrograms/index.tsx, frontend/src/containers/MergeWorkPrograms/logics.ts, frontend/src/containers/MergeWorkPrograms/reducer.ts, frontend/src/containers/MergeWorkPrograms/types.d.ts
Откатила часть правок. Локально как работало, так и работает. Будем тестировать гипотезы, значит
=> Еще одна попытка починить поиск

frontend/src/containers/DodProfile/DodProfile.styles.ts, frontend/src/containers/DodProfile/DodProfile.tsx, frontend/src/containers/MergeWorkPrograms/index.tsx
=> Dod profile fixes

frontend/src/containers/EducationalProgram/Characteristic/CompetenceMatrix/CompetenceMatrix.tsx, frontend/src/containers/EducationalProgram/Characteristic/CompetenceMatrix/types.d.ts
=> Add indicators to disciplines headings

application/workprogramsapp/admin.py, application/workprogramsapp/models.py, application/workprogramsapp/serializers.py, application/workprogramsapp/urls.py, application/workprogramsapp/views.py
Reverts TonikX/analytics_backend#251
=> Revert "Work program sources modifications"

frontend/src/containers/DodProfile/DodProfile.tsx, frontend/src/containers/EmailWidget/EmailWidget.styles.ts, frontend/src/containers/EmailWidget/EmailWidget.tsx, frontend/src/containers/EmailWidget/UserSelector/UserSelector.connect.ts, frontend/src/containers/EmailWidget/UserSelector/UserSelector.styles.ts, frontend/src/containers/EmailWidget/UserSelector/UserSelector.tsx, frontend/src/containers/EmailWidget/UserSelector/index.ts, frontend/src/containers/EmailWidget/UserSelector/type.d.ts, frontend/src/containers/EmailWidget/actions.ts, frontend/src/containers/EmailWidget/enum.ts, frontend/src/containers/EmailWidget/index.tsx, frontend/src/containers/EmailWidget/logics.ts, frontend/src/containers/EmailWidget/service.ts, frontend/src/containers/EmailWidget/types.d.ts, frontend/src/store/logics.ts
=> Email-рассылка в DodProfile

frontend/src/components/Header/Header.tsx, frontend/src/containers/UserSettings/UserSettings.tsx
=> Fix typo and add not verified icon

frontend/src/containers/EmailWidget/EmailWidget.tsx, frontend/src/containers/EmailWidget/logics.ts, frontend/src/containers/EmailWidget/service.ts
Рассылка для всех (кто на это подписался 😀)
=> Send to all

application/workprogramsapp/models.py, application/workprogramsapp/serializers.py
Обновил круд (там где это имело смысл) и сериализер для просмотра учебного плана.
=> disciplineblock father update

frontend/src/containers/WorkProgram/Competences/IndicatorDialog/IndicatorDialog.styles.ts, frontend/src/containers/WorkProgram/Competences/IndicatorDialog/IndicatorDialog.tsx
=> Add tooltip

frontend/src/components/AddLiteratureModal/index.tsx
=> Fix sourses

frontend/src/containers/WorkProgram/enum.ts, frontend/src/containers/WorkProgramList/CreateModal/CreateModal.connect.ts, frontend/src/containers/WorkProgramList/CreateModal/CreateModal.styles.ts, frontend/src/containers/WorkProgramList/CreateModal/CreateModal.tsx, frontend/src/containers/WorkProgramList/CreateModal/types.d.ts
=> New rpd modal

frontend/src/containers/WorkProgram/enum.ts, frontend/src/containers/WorkProgramList/CreateModal/CreateModal.tsx, frontend/src/containers/WorkProgramList/CreateModal/EditableRow/EditableRow.styles.ts, frontend/src/containers/WorkProgramList/CreateModal/EditableRow/EditableRow.tsx, frontend/src/containers/WorkProgramList/CreateModal/EditableRow/enum.ts, frontend/src/containers/WorkProgramList/CreateModal/types.d.ts
Добавила в модалку часы в зависимости от семестров
Старый калькулятор затащить не удалось, поэтому отображение писала с нуля, и валидации тут нет (можно ввести любые цифры)
=> Rpd modal extended

application/records/serializers.py, application/records/urls.py, application/records/views.py, application/workprogramsapp/disciplineblockmodules/search_filters.py, application/workprogramsapp/disciplineblockmodules/views.py
Поиск для блоков можно осуществлять по следующим полям:
id, module_isu_id, name, descipline_block__name
Чтобы поиск был нестрогий, нужно после имени поля написать приставку __icontains
Пример /api/disciplineblockmodule/short?name__icontains=естественн
=> Blockmodule search + statistic update

frontend/src/containers/FinalCertification/Steps/GeneralProvisions/index.tsx, frontend/src/containers/FinalCertification/Steps/styles.ts
=> Fix question mark position

frontend/src/containers/WorkProgram/enum.ts, frontend/src/containers/WorkProgramList/CreateModal/CreateModal.styles.ts, frontend/src/containers/WorkProgramList/CreateModal/CreateModal.tsx, frontend/src/containers/WorkProgramList/CreateModal/EditableRow/EditableRow.tsx, frontend/src/containers/WorkProgramList/CreateModal/EditableRow/enum.ts, frontend/src/containers/WorkProgramList/CreateModal/types.d.ts
=> New fields

frontend/src/containers/WorkProgram/General/FirstStep.connect.ts, frontend/src/containers/WorkProgram/General/FirstStep.tsx, frontend/src/containers/WorkProgram/General/types.d.ts, frontend/src/containers/WorkProgram/IntermediateCertification/IntermediateCertification.connect.ts, frontend/src/containers/WorkProgram/IntermediateCertification/IntermediateCertification.tsx, frontend/src/containers/WorkProgram/IntermediateCertification/types.d.ts, frontend/src/containers/WorkProgram/Sections/Sections.tsx, frontend/src/containers/WorkProgram/enum.ts
Tсли work_program_in_change_block пустое, все можно, если не пустое, блокируются эти поля и создание аттестационных оценочых средств
=> Block fields in rpd conditionally

frontend/src/containers/WorkProgram/Sections/Sections.connect.ts, frontend/src/containers/WorkProgram/Sections/Sections.tsx, frontend/src/containers/WorkProgram/Sections/types.d.ts, frontend/src/containers/WorkProgramList/CreateModal/CreateModal.tsx
=> Add contact hours

frontend/src/containers/WorkProgramList/CreateModal/CreateModal.tsx, frontend/src/containers/WorkProgramList/CreateModal/EditableRow/EditableRow.tsx, frontend/src/containers/WorkProgramList/CreateModal/types.d.ts
=> Disable consultation fields for offline

frontend/src/containers/Practice/Steps/Competences/Competences.tsx, frontend/src/containers/Practice/Steps/Competences/IndicatorDialog/IndicatorDialog.tsx, frontend/src/containers/Practice/Steps/Competences/PlansSelector/Selector.tsx, frontend/src/containers/Practice/Steps/Competences/PlansSelector/index.ts, frontend/src/containers/Practice/Steps/Competences/PlansSelector/types.d.ts, frontend/src/containers/Practice/Steps/Prerequisites/index.tsx, frontend/src/containers/Practice/Steps/Results/CreateModal/CreateModal.connect.ts, frontend/src/containers/Practice/Steps/Results/CreateModal/CreateModal.styles.ts, frontend/src/containers/Practice/Steps/Results/CreateModal/CreateModal.tsx, frontend/src/containers/Practice/Steps/Results/CreateModal/index.ts, frontend/src/containers/Practice/Steps/Results/CreateModal/types.d.ts, frontend/src/containers/Practice/Steps/Results/Results.connect.ts, frontend/src/containers/Practice/Steps/Results/Results.styles.ts, frontend/src/containers/Practice/Steps/Results/Results.tsx, frontend/src/containers/Practice/Steps/Results/ResultsSeletor/Selector.tsx, frontend/src/containers/Practice/Steps/Results/ResultsSeletor/index.ts, frontend/src/containers/Practice/Steps/Results/ResultsSeletor/types.d.ts, frontend/src/containers/Practice/Steps/Results/index.ts, frontend/src/containers/Practice/Steps/Results/types.d.ts, frontend/src/containers/Practice/actions.ts, frontend/src/containers/Practice/constants.tsx, frontend/src/containers/Practice/enum.ts, frontend/src/containers/Practice/getters.ts, frontend/src/containers/Practice/logics.ts, frontend/src/containers/Practice/reducers.ts, frontend/src/containers/Practice/service.ts, frontend/src/containers/Practice/types.d.ts
=> Results & Competences

frontend/src/containers/AddModuleToPlan/AddModuleToPlan.styles.ts, frontend/src/containers/AddModuleToPlan/AddModuleToPlan.tsx, frontend/src/containers/AddModuleToPlan/BlockSelector/BlockSelector.tsx, frontend/src/containers/AddModuleToPlan/BlockSelector/index.tsx, frontend/src/containers/AddModuleToPlan/EducationalPlans/EducationalPlans.tsx, frontend/src/containers/AddModuleToPlan/EducationalPlans/index.tsx, frontend/src/containers/AddModuleToPlan/Modules/Modules.tsx, frontend/src/containers/AddModuleToPlan/Modules/index.tsx, frontend/src/containers/AddModuleToPlan/actions.ts, frontend/src/containers/AddModuleToPlan/enum.ts, frontend/src/containers/AddModuleToPlan/getters.ts, frontend/src/containers/AddModuleToPlan/index.tsx, frontend/src/containers/AddModuleToPlan/logics.ts, frontend/src/containers/AddModuleToPlan/reducer.ts, frontend/src/containers/AddModuleToPlan/service.ts, frontend/src/containers/AddModuleToPlan/types.d.ts, frontend/src/containers/DodProfile/DodProfile.styles.ts, frontend/src/containers/DodProfile/DodProfile.tsx, frontend/src/containers/Practice/constants.tsx, frontend/src/store/logics.ts, frontend/src/store/reducers.ts
=> New dod modal

frontend/src/containers/AddModuleToPlan/AddModuleToPlan.styles.ts, frontend/src/containers/AddModuleToPlan/AddModuleToPlan.tsx, frontend/src/containers/AddModuleToPlan/BlockSelector/BlockSelector.tsx, frontend/src/containers/AddModuleToPlan/EducationalPlans/EducationalPlans.tsx, frontend/src/containers/AddModuleToPlan/Modules/Modules.tsx, frontend/src/containers/AddModuleToPlan/SelectedPlans/SelectedPlans.tsx, frontend/src/containers/AddModuleToPlan/SelectedPlans/index.tsx, frontend/src/containers/AddModuleToPlan/actions.ts, frontend/src/containers/AddModuleToPlan/enum.ts, frontend/src/containers/AddModuleToPlan/getters.ts, frontend/src/containers/AddModuleToPlan/logics.ts, frontend/src/containers/AddModuleToPlan/reducer.ts, frontend/src/containers/AddModuleToPlan/service.ts, frontend/src/containers/AddModuleToPlan/types.d.ts
=> Dod modal fixes

frontend/src/containers/FinalCertification/Steps/DisabledPeopleInfo/index.tsx, frontend/src/containers/FinalCertification/Steps/GeneralProvisions/index.tsx, frontend/src/containers/FinalCertification/Steps/styles.ts, frontend/src/containers/FinalCertification/styles.ts, frontend/src/containers/Practice/Practice.styles.ts, frontend/src/containers/Practice/Steps/Assessment/index.tsx, frontend/src/containers/Practice/Steps/DisabledPeopleInfo/index.tsx, frontend/src/containers/Practice/Steps/GeneralProvisions/index.tsx, frontend/src/containers/Practice/Steps/PlansAndDirections/index.tsx, frontend/src/containers/Practice/Steps/Prerequisites/index.tsx, frontend/src/containers/Practice/Steps/Structure/index.tsx, frontend/src/containers/Practice/Steps/styles.ts, frontend/src/containers/Practice/constants.tsx
Тут пока все кроме ISU ID — его нужно обсудить
=> Gia / practice fixes

frontend/src/containers/EducationalProgram/Characteristic/CompetenceMatrix/CompetenceMatrix.tsx, frontend/src/containers/EducationalProgram/Characteristic/CompetenceMatrix/types.d.ts
=> Matrix nested

frontend/src/containers/EducationalProgram/Characteristic/CompetenceMatrix/CompetenceMatrix.tsx
=> Leave only numbers

frontend/src/containers/EducationalProgram/Characteristic/CompetenceMatrix/CompetenceMatrix.tsx, frontend/src/containers/EducationalProgram/Characteristic/CompetenceMatrix/IndicatorsDialog/IndicatorDialog.tsx, frontend/src/containers/EducationalProgram/logics.ts, frontend/src/containers/EducationalProgram/service.ts
1. Cleared indicator modal
2. Changed endpoint
3. Deleted plan selector
4. Added indicators shortened names with tooltips
=> Matrix bugfixes

frontend/src/containers/EducationalProgram/Characteristic/CompetenceMatrix/CompetenceMatrix.styles.ts, frontend/src/containers/EducationalProgram/Characteristic/CompetenceMatrix/CompetenceMatrix.tsx
=> Adjust matrix columns

frontend/src/containers/FinalCertification/actions.ts, frontend/src/containers/FinalCertification/components/Download/index.tsx, frontend/src/containers/FinalCertification/components/Download/styles.ts, frontend/src/containers/FinalCertification/enum.ts, frontend/src/containers/FinalCertification/logics.ts, frontend/src/containers/FinalCertification/service.ts, frontend/src/containers/FinalCertification/types.d.ts, frontend/src/containers/Practice/actions.ts, frontend/src/containers/Practice/components/Download/index.tsx, frontend/src/containers/Practice/components/Download/styles.ts, frontend/src/containers/Practice/enum.ts, frontend/src/containers/Practice/logics.ts, frontend/src/containers/Practice/service.ts, frontend/src/containers/Practice/types.d.ts
=> Add ISU buttons

application/workprogramsapp/educational_program/process_modules_for_matrix.py, application/workprogramsapp/files_export/general_characteristic_export.py, application/workprogramsapp/files_export/views.py
1. Теперь в скачивателе ОХ не выкидывает ошибку на аннотации
2. В матрице компетенций (веб-версия) при нескольких ОХ не выводятся пустые модули и блоки
=> gh downloader update and competence matrix remove duplicates

application/workprogramsapp/management/commands/get_all_wps_without_standard.py
Команда: `get_all_wps_without_standard`
Вывод находится в `workprogramsapp/management/commands/files/wp_without_standards.json`
=> command to get all wps without standards

application/workprogramsapp/educational_program/views.py, application/workprogramsapp/workprogram_additions/views.py
Для `api/competence/get_all_ap_with_competences_and_indicators_to_wp` сделаны фильтры
ap_id - id объекта AcademicPlan для фильтрации
imp_id - id объекта ImplementationAcademicPlan для фильтрации
year - фильтр по годам УП
=> isu gia practice fiction fields

application/workprogramsapp/isu_merge/academic_plan_update/isu_service.py, application/workprogramsapp/management/commands/create_new_wp_from_isu.py
Запуск команды:
`manage.py create_new_wp_from_isu
`
=> wp from isu bank managment

application/workprogramsapp/isu_merge/post_to_isu/ap_to_isu.py, application/workprogramsapp/isu_merge/post_to_isu/updaters_isu_logic.py, application/workprogramsapp/serializers.py, application/workprogramsapp/views.py
для указания направления при создании УП нужно указать его айди в поле fos_pk
=>  creation ap with FOS

frontend/src/containers/Practice/Steps/Results/CreateModal/CreateModal.tsx, frontend/src/containers/WorkProgram/Prerequisites/CreateModal/CreateModal.tsx
=> Убрала кнопку "Создать учебную сущность"

application/workprogramsapp/disciplineblockmodules/serializers.py, application/workprogramsapp/disciplineblockmodules/views.py, application/workprogramsapp/files_export/competence_matrix_export.py, application/workprogramsapp/files_export/views.py, application/workprogramsapp/isu_merge/post_to_isu/updaters_isu_logic.py, application/workprogramsapp/permissions.py, application/workprogramsapp/serializers.py
1. Фиксы для отправки УП в ИСУ
2. Теперь при создании УП руками год будет устанавливаться корректно
3. Профессиональные компетенции при скачивании матрицы отображаются корректно
=> Gh ap fixes

application/media/bugs_log/user_1/Основные_средства.xls, application/media/bugs_log/user_1/Основные_средства_aHhk9Q0.xls, application/media/bugs_log/user_1/Основные_средства_pHEkgzu.xls, application/workprogramsapp/isu_merge/academic_plan_headers.py, frontend/src/containers/EducationalPlan/TrainingModules/DetailTrainingModule/DetailTrainingModule.styles.ts, frontend/src/containers/EducationalPlan/TrainingModules/DetailTrainingModule/DetailTrainingModule.tsx, frontend/src/containers/EducationalProgram/Characteristic/Characteristic.styles.ts, frontend/src/layout/logics.ts
Reverts TonikX/analytics_backend#478
=> Revert "Fix scroll"

frontend/src/containers/EducationalProgram/Characteristic/Characteristic.styles.ts
=> Fix scroll in competence matrix
